### ISSUE TITLE
Typo Episode 4 Closing Argument

### ISSUE THREAD

**Issue by fredfrog6** [ScarletStudy/DGS1-3DS-Release#71] opened 2019-04-10 00:38 UTC
During the closing argument Naruhodou says that the defendant went to The Ragged Reader when Naruhodou had previously stated that Souseki went to Tattered Tales instead.

**Comment by interborough** [comment] 2019-04-10 02:09
I can confirm that this is an issue - I encountered the same problem when I went through case 4 awhile ago.

**Comment by keksdee** [comment] 2019-04-10 13:44
I'm having a lot of trouble finding where this issue is. Do either of you remember any exact quotes from that part? In fact, the only instance of ``reader`` that I can find during the CA is Juror 6's statement.

**Comment by interborough** [comment] 2019-04-10 19:18
I can't remember the exact quote at the moment - I'll play through that section again and get back to you when I do. I played through case 4 when it was originally released a few months back (so my memory of it isn't the best - but I do remember being confused by the wrong bookstore name being used at one point), and I assumed that it was fixed already - but seeing as this was reported yesterday I suppose not. Maybe the original reporter can shine some more light on this until I get time to play through that section again.

**Comment by fredfrog6** [comment] 2019-04-10 19:51
I believe that it was either when pressing juror 6 or juror 3 although it may have been when clashing the two statements if my memory serves correctly.

**Comment by interborough** [comment] 2019-04-10 21:31
So I just played through case 4 past the first closing argument, and I can't find the mistake either. I'm on the current version (2.4.0), but I could've sworn that a bookstore name was wrong on a previous patch. Maybe it was already fixed, because I believe that the line after finding the clash between Juror 2 and Juror 6 that says "The defendant bought books from Tattered Tales and walked home from there" originally said the Ragged Reader upon case 4's release a few months back, but it seems fine now. I'm not entirely sure though, but I didn't find anything else either...

**Comment by fredfrog6** [comment] 2019-04-10 21:38
I thought I was on the current version but it looks like something went wrong and I was on 2.3 not 2.4. It may have been fixed in the most recent version.

**Closed** 2019-11-01 14:52 UTC
