### ISSUE TITLE
Few typos here and there -  Chapter 1 Trial 1-1

### ISSUE THREAD

**Issue by fulyflea** [ScarletStudy/DGS1-3DS-Release#22] opened 2018-01-03 11:30 UTC
When the 2nd statement of the 1st cross examination is pressed, a green block of text appears.
![img_1490](https://user-images.githubusercontent.com/35005061/34514044-4c4cb2fc-f0a6-11e7-9224-ec80b5ffe9e3.jpg)
In the backlog, that green text dissappears.
![img_1491](https://user-images.githubusercontent.com/35005061/34514085-721d3588-f0a6-11e7-9650-f80982d072c4.jpg)

When the postmortem is presented in the 4th statement, there is a missing comma in the sentence shown below. If the photograph were to be presented instead, the comma is present.
![img_1487](https://user-images.githubusercontent.com/35005061/34514032-3ce9b7ba-f0a6-11e7-9886-0f5bdfb5cef4.jpg)

In the revised translation, 'prosuction' -> prosecution
![img_1488](https://user-images.githubusercontent.com/35005061/34514200-26811b48-f0a7-11e7-947e-2746b121dd16.jpg)

**Comment by Hyarion-SS** [comment] 2018-01-03 14:01
Thanks - the green text/missing backlog screenshots are the first solid evidence we've had of the cause behind some seemingly random issues. I believe that the issue as a whole should be fixed now, but any screenshots of other oddities (notably backlog) would be welcome as they should help confirm or disprove this.

**Closed** 2018-09-22 09:54 UTC
